---
title: "Review1 - Accidents analysis"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---
### Reg. No: 18BCE1237

### Name: Aakash Ratha

## Setup


## What problem are you trying to solve?

I actually want to analyze and understand the reasons behind the accidents taking place so frequently. This analysis 
can help drivers who are driving for the first time on that particular place. This analysis will definitely minimise 
the number of accidents.


## What data have you chosen?(Chosen Dataset, Source of dataset, Description of dataset, basic commands to describe dataset)

I have used the Dataset from kaggle. Link for this Dataset : https://www.kaggle.com/sobhanmoosavi/us-accidents
This is a countrywide car accident Dataset, which covers 49 states of the USA. The accident data is collected from February 2016 to June 2020.Currently, there are about 3.5 million accident records in this dataset.

This Dataset can be used for numerous applications such as real-time accident prediction, studying accident hotspot locations, casualty analysis and extracting cause and effect rules to predict accidents, or studying the impact of precipitation or other environmental stimuli on accident occurrence.

Sample
```{r}
data=read.csv("US_Accidents_June20.csv")
View(data)
dim(data)
str(data)
head(data)
tail(data)
colnames(data)
```


## Frame your objectives

1. Complete analysis of each accident.

2. Understanding the factors due to which accident takes place.

3. Data Visualization

4. Developing some kind of algorithm which helps the driver to identify accident zones in order to reduce the count of accidents taking place.

5. Predicting results with the help of existing R models.

## Is there any work previously reported on the problem and the data? If so, discuss it here.

Every month this data is getting updated as the traffic condition and road conditions are also rapidly changing. Many people have done research on the old data, since this data is getting updated frequently on monthly basis, that's the reason why still analysis is going on.



